import type { Metadata } from "next";
import '@/styles/globals.css';
import Nav from "@/components/Nav/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={'antialiased'}
      >
        <Nav></Nav>
        {children}
      </body>
    </html>
  );
}
